/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mycompany.app;

public class App {


    public static void main(String[] args) {
        System.out.println("Does nothing");
    }
}
